[Service]
ReadWritePaths=/etc/unbound
ReadWritePaths=/etc/chrony
ReadWritePaths=/etc/systemd
ReadWritePaths=/etc/suricata
ReadWritePaths=/etc/kea
ReadWritePaths=/etc/dhcp
ReadWritePaths=/var/lib/dhcp
ReadWritePaths=/var/lib/dhclient
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_RAW CAP_NET_BIND_SERVICE CAP_SYS_ADMIN
